ablog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myblog.urls')),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path 
from .views import UserRegisterView , UserEditView ,PasswordsChangeView , ShowProfilePageView ,EditProfilePageView , CreateProfilePageViwe
#from django.contrib.auth import views as auth_views
from . import views

app_name = "members"
urlpatterns = [
    
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    #path('password/' , auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html'), name='password'),
    path('password/',  PasswordsChangeView.as_view(template_name='registration/change-password.html'),name='password'),
    path('password_success/', views.password_success , name='password_success'),
    path('<int:pk>/profile/' ,  ShowProfilePageView.as_view() , name='show_profil_page'),
    path('<int:pk>/edit_profile_page/' ,EditProfilePageView.as_view() , name='edit_profil_page'),
    path('create_profil_page/' ,  CreateProfilePageViwe.as_view() , name='create_profil_page'),


    ###################### admin mastar ##############

 


]

myblog/urls.py
from django.urls import path 
from . import views
from .views import HomeView , ArticleDetalView , CategorylistView, AddPostView , UpdatePostView ,DeletePostView , AddCategorView , CategoryView ,likeView ,AddCommentView , AdminLoginView ,AdminHome , courMView , AboutView

app_name = "myblog"
urlpatterns = [
 
  #path('', views.home, name="home"),
  path('', HomeView.as_view(), name="home"),
  path('articl/<int:pk>',ArticleDetalView.as_view(),name='article_detaile'),
  path('add_post/' , AddPostView.as_view() , name='add_post'),
  path('add_category/' , AddCategorView.as_view() , name='add_category'),
  path('article/edit/<int:pk>' , UpdatePostView.as_view() , name='updet_post'),
  path('article/<int:pk>/remove' , DeletePostView.as_view() , name='delete_post'),
  path('category/<str:cats>/', CategoryView, name='category'),
  path('category-list/',CategorylistView, name='category-list'),
  path('like/<int:pk>', likeView, name='like_post'),
  path('article/<int:pk>/comment/', AddCommentView.as_view(),name='add_comment'),
   path('about/', AboutView.as_view() , name= 'about'),
############ admin path ##########

path("admin-login/" , AdminLoginView.as_view() , name="admin"),
path("admin-home/" , AdminHome.as_view(), name="adminhome"),
path('motaki_dris/' , views.courMView , name='motaki_dris'),


]

myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime , date
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
#hadi ila bgiti thadad lma3lomat ligatmchi liha page mora may3amar Post 
        return reverse('myblog:home')   

####### admin model ######
class Admin(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200, null=True , blank=True)
    image = models.ImageField(upload_to="admins")
    mobel =models.CharField(max_length=20 , blank=True , null=True)

    def __str__(self):
        return self.user.username


class Profile(models.Model):
    user = models.OneToOneField(User, null=True , on_delete=models.CASCADE )
    bio = models.TextField(max_length=600)
    profile_pic = models.ImageField(null=True ,blank=True,upload_to="images/profile/")
    website_url = models.CharField(max_length=255 , null=True , blank=True)
    facebook_url = models.CharField(max_length=255 , null=True , blank=True)
    twitter_url = models.CharField(max_length=255 , null=True , blank=True)
    instagram_url = models.CharField(max_length=255 , null=True , blank=True)
    pinterest_url = models.CharField(max_length=255 , null=True , blank=True)
    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        #hadi ila bgiti thadad lma3lomat ligatmchi liha page mora may3amar Post 
        return reverse('myblog:home')     

class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True ,blank=True,upload_to="images/")
    title_tag = models.CharField(max_length=255 ,null=True , blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body =RichTextField(blank=True, null=True)
    #body =models.TextField()
    post_date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=255,default='coding')
    snipped = models.CharField(max_length=255)
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        #hadi gay"amar dik form kamal idan jadwal d Post kolch 
        #return reverse('myblog:article_detaile' , args=(str(self.id)))
        #hadi ila bgiti thadad lma3lomat ligatmchi liha page mora may3amar Post 
        return reverse('myblog:home' ,)


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments" , on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

myblog/forms.py
from django import forms
from .models import Post , Category ,  Comment 


#choices = [('coding','coding'),('sports', 'sports'),('enteretainment', 'entertainment'),]

choices = Category.objects.all().values_list('name','name')
#
choices_list=[]
for item in choices:
    choices_list.append(item)

class PostForms(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', "title_tag", "author", "category", "body" ,"snipped" ,"header_image")

        widgets = {
            'title': forms.TextInput(attrs={ 'class':"form-control" , "placeholder":"This is Titel Placeholder "}),
            'title_tag': forms.TextInput(attrs={ 'class':"form-control"}),
            'author': forms.TextInput(attrs={ 'class':"form-control", 'value':'' ,'id':'elder','type':'hidden'}),
            #'author': forms.Select(attrs={ 'class':"form-control"}),
            'category': forms.Select(choices=choices_list, attrs={ 'class':"form-control"}),
            'body': forms.Textarea(attrs={ 'class':"form-control"}),
            'snipped': forms.Textarea(attrs={ 'class':"form-control"}),     
             
        }
class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', "title_tag","body" , "snipped")

        widgets = {
            'title': forms.TextInput(attrs={ 'class':"form-control" , "placeholder":"This is Titel Placeholder "}),
            'title_tag': forms.TextInput(attrs={ 'class':"form-control"}),
            'body': forms.Textarea(attrs={ 'class':"form-control"}),
            'snipped': forms.Textarea(attrs={ 'class':"form-control"}),
        
             
        }
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ('name','body')


        widgets = {
            'name': forms.TextInput(attrs={ 'class':"form-control" , "placeholder":"This is name User  "}),
            'body': forms.Textarea(attrs={ 'class':"form-control"}),


        } 

class AdminLoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control ",}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        "class" : "form-control",}))

myblog/views.py
from django.shortcuts import render , get_object_or_404 , redirect 
from django.contrib.auth import authenticate , login , logout
from django.views.generic import View, TemplateView , ListView, DetailView ,CreateView , UpdateView , DeleteView , FormView
from .models import Post , Category , Comment , Admin
from .forms import PostForms ,EditForm , CommentForm ,AdminLoginForm
from members.forms import  ProfilePageForm
from django.urls import reverse_lazy
from django.urls import  reverse_lazy , reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator

#def home(request):
#   post=Post.objects.all()
#    return render(request,'home.html',{'post:post'})
def likeView(request,pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
         post.likes.add(request.user)
         liked = True
    return HttpResponseRedirect(reverse('myblog:article_detaile', args=[str(pk)]))


class HomeView(ListView):

    model= Post
    template_name = 'home.html'
    paginate_by = 4
    ordering = ['-post_date']

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context['cat_menu'] = cat_menu
        return context 

def CategorylistView(request):
    cat_menu_list= Category.objects.all()  
    return render(request, 'category_list.html' , {'cat_menu_list':cat_menu_list})


def CategoryView(request,cats):
    category_posts = Post.objects.filter(category=cats.replace('-' , ' ', ))
    return render(request, 'categories.html' ,{'cats':cats.title().replace('-' , ' ') , 'category_posts':category_posts})


class AboutView(TemplateView ):

    template_name = "about.html"

class ArticleDetalView(DetailView):
    model = Post
    #form_class  = PostForms
    template_name = 'articl_details.html'

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(ArticleDetalView, self).get_context_data(*args, **kwargs)

        stuff= get_object_or_404(Post,id=self.kwargs['pk'])
        total_likes = stuff.total_likes()
        
        liked = False
        if stuff.likes.filter(id=self.request.user.id).exists():
            liked = True 

        context['cat_menu'] = cat_menu
        context["total_likes"]= total_likes
        context["liked"] = liked
        return context      

class AddPostView(CreateView):
    model = Post
    form_class  = PostForms
    template_name = 'add_post.html'
    #hadi ila gay3amar post kalala o bkolchi lihadatih f jadwal d post 
    #fields = '__all__'
    #hadi  gay3amar dikchi ligathaddlo nta hna bla b jadwal li model
    #fields = ('title', 'body')

class AddCommentView(CreateView):
    model = Comment
    form_class  = CommentForm 
    #fields = '__all__'  
    template_name = 'add_comment.html'
    def form_valid(self,form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('myblog:home')
      
class AddCategorView(CreateView):
    model = Category
    #form_class  = PostForms
    template_name = 'add_category.html'
    #hadi ila gay3amar post kalala o bkolchi lihadatih f jadwal d post 
    fields = '__all__'
    #hadi  gay3amar dikchi ligathaddlo nta hna bla b jadwal li model
    #fields = ('title', 'body')

class UpdatePostView(UpdateView):
    model = Post
    template_name = 'update_post.html'
    form_class  = EditForm
    #fields = ['title' , 'title_tag','body']    

class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('myblog:home') 


######## view admin ######

class AdminLoginView(FormView):
    template_name = "adminpage/adminlogin.html"
    form_class = AdminLoginForm
    success_url = reverse_lazy("myblog:adminhome")

    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and Admin.objects.filter(user=usr).exists():
            login(self.request,usr)
        else:
             return render(self.request , self.template_name , {"form":self.form_class,"error":"Invalid credentails"})

        return super().form_valid(form)     

class AdminHome(TemplateView):

    template_name = "adminpage/adminhome.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and Admin.objects.filter(user=request.user).exists():
            pass
        else:
            return redirect("/admin-login/")
        return super().dispatch(request,*args ,**kwargs)

    def get_context_data(self, *args, **kwargs):
        cat_menu_admin = Post.objects.all()
        context = super(AdminHome, self).get_context_data(*args, **kwargs)
        context['cat_menu_admin'] = cat_menu_admin
        return context

def courMView(request):
    context = []
    return render(request, 'adminpage/motaki_dris.html' ,{})




##### 19:44

myblog/templates/adminpage/adminbase.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Home Admin {% endblock %}</title>
        
         <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/mainepage.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/style.css' %}"> 
        <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/folter.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/bolog_detil.css' %}">
       <link rel="stylesheet" href="{% static 'myblog/css/styleadmin.css' %}">
       <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/liststyl.css' %}">
      
        <script
        src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
        crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
       
      <script>
            $(function() {
            $(".toggle").on("click", function() {
                if ($(".item").hasClass("active")) {
                    $(".item").removeClass("active");
                } else {
                    $(".item").addClass("active");
                }
            });
        });
       

   
   </script> 
    </head>
   

<body>
 
    <nav>
        <ul class="menu">
            
            <li class="logo"><img src="{% static 'myblog/images/logo_mastare.png'  %}"  width="60pox"  height="60px" alt="nature" class="logo"></li>
            <li class="item">  <i class="fas fa-home"></i><a href="{% url 'myblog:adminhome'  %}" >Home</a></li>
          
            {% if user.is_authenticated   %}
            <li class="item"><i class="fas fa-plus-square"></i><a href="{% url 'myblog:add_post'  %} " target="_blank" > Add Post</a></li>
            <li class="item"> <i class="fas fa-folder-plus"></i><a href="{% url 'myblog:add_category'  %}" target="_blank" > Add Category</a></li>
            
            {% endif %}
            <li class="item"> <i class="fas fa-question-circle"></i><a href="{% url 'myblog:motaki_dris'  %}" target="_blank" > Help</a></li>
           
            
            <li class="item"><i class="fas fa-eye"></i><a href="{% url 'myblog:home'   %}" target="_blank">Veset site</a></li>
            <li class="toggle"><span class="bars"></span></li>
        </ul>
    </nav>

 

  
        {% block content%}




        {% endblock %}


        <footer>
            <div class="containeree">
                <div class="ftr">
                    <h3>About</h3>
                    <ul class="containeree">
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Work</a></li>
                    </ul>
                </div>
                <div class="ftr">
                    <h3>Contact</h3>
                    <ul class="containeree">
                        <li><a href="#">info@gmail.com</a></li>
                        <li><a href="#">(707) 322-22-322</a></li>
                        <li><a href="#">Richmond,VA,2203</a></li>
                    </ul>
                </div>
                <div class="ftr">
                    <h3>Social</h3>
                    <ul class="containeree">
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Instagram</a></li>
                    </ul>
                </div>
                <div class="ftr">
                    <h3>Join Our Newsletter</h3>
                    <form action="#">
                        <input type="email" placeholder="Enter Your Email." required>
                        <div class="btn">
                            <input type="submit" value="Subscribe">
                        </div>
                    </form>
                </div>
    
            </div>
        </footer>


        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>

</html>

myblog/templates/adminpage/adminhome.html
{% extends "adminpage/adminbase.html" %}
{% load static %}
{% block title %} Admin Home  {% endblock %}

{% block content %}

 <!-- stsrte servece-->
 <div class="container">
 <div class="services-section">
  <div class="inner-width">
    <h1 class="section-title">Semestre 8</h1>
    <div class="border"></div>
    <div class="services-container">

      <div class="service-box">
        <div class="service-icon">
          <i class="fas fa-user-graduate"></i>
          
        </div>
        <div class="service-title"> Mr.ZANATI Driss</div>
        <div class="service-desc">
          <a class="test" href="{% url 'myblog:motaki_dris'  %}">Système Bancaire Participatif</a>
        </div>
      </div>

      <div class="service-box">
        <div class="service-icon">
          <i class="fas fa-user-graduate"></i>
        </div>
        <div class="service-title">Mr.EL MOUTAQUI Badreddin</div>
        <div class="service-desc">
         <a class="test" href="{% url 'myblog:motaki_dris'  %}">Economie Politique Islamique</a>
        </div>
      </div>

      <div class="service-box">
        <div class="service-icon">
          <i class="fas fa-user-graduate"></i>
        </div>
        <div class="service-title">Mr.Profe </div>
        <div class="service-desc">
         <a  href="{% url 'myblog:motaki_dris'  %}"> Gestion de Portefeuille D'actifs Financiers</a>
        </div>
      </div>

      <div class="service-box">
        <div class="service-icon">
          <i class="fas fa-user-graduate"></i>
        </div>
        <div class="service-title">Mr.Prof</div>
        <div class="service-desc">
         <a  href="{% url 'myblog:motaki_dris'  %}"> Produits Dèrivès Et Stratègies De Couverture</a> 
        </div>
      </div>

      <div class="service-box">
        <div class="service-icon">
          <i class="fas fa-user-graduate"></i>
        </div>
        <div class="service-title">Mr. El ASSRI LAILA</div>
        <div class="service-desc">
         <a  href="{% url 'myblog:motaki_dris'  %}"> GRH Et MANAGEMENT INTERCULTUREL</a>
        </div>
      </div>

      <div class="service-box">
        <div class="service-icon">
          <i class="fas fa-user-graduate"></i>
        </div>
        <div class="service-title">Mr.TABAA YSSINE</div>
        <div class="service-desc">
         <a href="{% url 'myblog:motaki_dris'  %}">SYSTÈME D'INFORMATION EN FINANCE</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
 <!-- end servece-->
<!-- start list   -->
<!-- end list  -->

            {% for post in cat_menu_admin %}
            <div class="container main-container">
              <div class="row main-row">
                <div class="col-lg-4 col-md-12 col-sm-12">
                  <div class="blog-img">
                    {% if post.header_image %}
                         <img  src="{{post.header_image.url}}" alt="nature" class="img-fluid">
                      {% else %}
                      <img src="{% static 'myblog/images/images-test.png'  %}" alt="nature" class="img-fluid">   
                     
                     {% endif  %} 
                  <!--   <img src="{% static 'myblog/images/images-test.png'  %}" alt="nature" class="img-fluid">-->
                  </div>
                </div>
              
                <div class="col-lg-8 col-md-12 col-sm-12">
                  <div class="blog-title">
                    <h3><a class="title" href="{% url 'myblog:article_detaile' post.pk%}">{{post.title}}</a></h3>
                  </div>
                  <div class="blog-date">
                    <i class="fas fa-id-card"><span>{{post.author.first_name}} {{post.author.last_name}}</span></i>
            
                    <i class="far fa-calendar-minus"><span>{{post.post_date}}</span></i> 
                    <i class="fas fa-book "><span><a href="{% url 'myblog:category' post.category|slugify %}">{{post.category}} </a> </span></i>
                    <i class="fas fa-heart" ><span>{{post.total_likes}}</span></i>
                  </div>
                  <div class="blog-desc">
                    <p>
                      {{post.snipped}}
                    </p> 
                  </div>
                  
                  <div class="blog-read-more">
                    <h6><a class="btn btn-outline-dark" href="{% url 'myblog:article_detaile' post.pk%}">{{post.title}}</a></h6><br>
                    <!--
                    <button class="btn btn-outline-dark">Read More</button>-->
                  </div>
                  
                </div>
              </div>
            </div>
            {% endfor  %}
{% endblock%}

myblog/templates/adminpage/adminlogin.html
{% extends 'base.html'  %}
{% block title%} Login Admin {%  endblock %}
{% block content %}


<h1>Login Admin..</h1>
<br>
<div class="form-group">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">Username:</label>
            <input type="text" class="form-control" name="username" placeholder="Enter Username">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Password:</label>
            <input type="password" class="form-control" name="password" placeholder="Enter password">

            
        </div>
     
    </div>
        <button class="btn btn-outline-secondary">Login Admin</button></br>
     </form>
     <br>
     <br>
     <!--
         Not Register? Sing Up Up Here...<a href="{% url 'members:register'  %}">Here</a>
        -->
    
   



{% endblock  %}