ablog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myblog.urls')),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path 
from .views import UserRegisterView , UserEditView ,PasswordsChangeView , ShowProfilePageView ,EditProfilePageView , CreateProfilePageViwe
#from django.contrib.auth import views as auth_views
from . import views

app_name = "members"
urlpatterns = [
    
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    #path('password/' , auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html'), name='password'),
    path('password/',  PasswordsChangeView.as_view(template_name='registration/change-password.html'),name='password'),
    path('password_success/', views.password_success , name='password_success'),
    path('<int:pk>/profile/' ,  ShowProfilePageView.as_view() , name='show_profil_page'),
    path('<int:pk>/edit_profile_page/' ,EditProfilePageView.as_view() , name='edit_profil_page'),
    path('create_profil_page/' ,  CreateProfilePageViwe.as_view() , name='create_profil_page'),


    ###################### admin mastar ##############

 


]

myblog/urls.py
from django.urls import path 
from . import views
from .views import HomeView , ArticleDetalView , CategorylistView, AddPostView , UpdatePostView ,DeletePostView , AddCategorView , CategoryView ,likeView ,AddCommentView , AdminLoginView ,AdminHome , courMView , AboutView

app_name = "myblog"
urlpatterns = [
 
  #path('', views.home, name="home"),
  path('', HomeView.as_view(), name="home"),
  path('articl/<int:pk>',ArticleDetalView.as_view(),name='article_detaile'),
  path('add_post/' , AddPostView.as_view() , name='add_post'),
  path('add_category/' , AddCategorView.as_view() , name='add_category'),
  path('article/edit/<int:pk>' , UpdatePostView.as_view() , name='updet_post'),
  path('article/<int:pk>/remove' , DeletePostView.as_view() , name='delete_post'),
  path('category/<str:cats>/', CategoryView, name='category'),
  path('category-list/',CategorylistView, name='category-list'),
  path('like/<int:pk>', likeView, name='like_post'),
  path('article/<int:pk>/comment/', AddCommentView.as_view(),name='add_comment'),
   path('about/', AboutView.as_view() , name= 'about'),
############ admin path ##########

path("admin-login/" , AdminLoginView.as_view() , name="admin"),
path("admin-home/" , AdminHome.as_view(), name="adminhome"),
path('motaki_dris/' , views.courMView , name='motaki_dris'),


]

myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime , date
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
#hadi ila bgiti thadad lma3lomat ligatmchi liha page mora may3amar Post 
        return reverse('myblog:home')   

####### admin model ######
class Admin(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200, null=True , blank=True)
    image = models.ImageField(upload_to="admins")
    mobel =models.CharField(max_length=20 , blank=True , null=True)

    def __str__(self):
        return self.user.username


class Profile(models.Model):
    user = models.OneToOneField(User, null=True , on_delete=models.CASCADE )
    bio = models.TextField(max_length=600)
    profile_pic = models.ImageField(null=True ,blank=True,upload_to="images/profile/")
    website_url = models.CharField(max_length=255 , null=True , blank=True)
    facebook_url = models.CharField(max_length=255 , null=True , blank=True)
    twitter_url = models.CharField(max_length=255 , null=True , blank=True)
    instagram_url = models.CharField(max_length=255 , null=True , blank=True)
    pinterest_url = models.CharField(max_length=255 , null=True , blank=True)
    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        #hadi ila bgiti thadad lma3lomat ligatmchi liha page mora may3amar Post 
        return reverse('myblog:home')     

class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True ,blank=True,upload_to="images/")
    title_tag = models.CharField(max_length=255 ,null=True , blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body =RichTextField(blank=True, null=True)
    #body =models.TextField()
    post_date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=255,default='coding')
    snipped = models.CharField(max_length=255)
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        #hadi gay"amar dik form kamal idan jadwal d Post kolch 
        #return reverse('myblog:article_detaile' , args=(str(self.id)))
        #hadi ila bgiti thadad lma3lomat ligatmchi liha page mora may3amar Post 
        return reverse('myblog:home' ,)


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments" , on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

myblog/forms.py
from django import forms
from .models import Post , Category ,  Comment 


#choices = [('coding','coding'),('sports', 'sports'),('enteretainment', 'entertainment'),]

choices = Category.objects.all().values_list('name','name')
#
choices_list=[]
for item in choices:
    choices_list.append(item)

class PostForms(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', "title_tag", "author", "category", "body" ,"snipped" ,"header_image")

        widgets = {
            'title': forms.TextInput(attrs={ 'class':"form-control" , "placeholder":"This is Titel Placeholder "}),
            'title_tag': forms.TextInput(attrs={ 'class':"form-control"}),
            'author': forms.TextInput(attrs={ 'class':"form-control", 'value':'' ,'id':'elder','type':'hidden'}),
            #'author': forms.Select(attrs={ 'class':"form-control"}),
            'category': forms.Select(choices=choices_list, attrs={ 'class':"form-control"}),
            'body': forms.Textarea(attrs={ 'class':"form-control"}),
            'snipped': forms.Textarea(attrs={ 'class':"form-control"}),     
             
        }
class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', "title_tag","body" , "snipped")

        widgets = {
            'title': forms.TextInput(attrs={ 'class':"form-control" , "placeholder":"This is Titel Placeholder "}),
            'title_tag': forms.TextInput(attrs={ 'class':"form-control"}),
            'body': forms.Textarea(attrs={ 'class':"form-control"}),
            'snipped': forms.Textarea(attrs={ 'class':"form-control"}),
        
             
        }
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ('name','body')


        widgets = {
            'name': forms.TextInput(attrs={ 'class':"form-control" , "placeholder":"This is name User  "}),
            'body': forms.Textarea(attrs={ 'class':"form-control"}),


        } 

class AdminLoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control ",}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        "class" : "form-control",}))

myblog/views.py
from django.shortcuts import render , get_object_or_404 , redirect 
from django.contrib.auth import authenticate , login , logout
from django.views.generic import View, TemplateView , ListView, DetailView ,CreateView , UpdateView , DeleteView , FormView
from .models import Post , Category , Comment , Admin
from .forms import PostForms ,EditForm , CommentForm ,AdminLoginForm
from members.forms import  ProfilePageForm
from django.urls import reverse_lazy
from django.urls import  reverse_lazy , reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator

#def home(request):
#   post=Post.objects.all()
#    return render(request,'home.html',{'post:post'})
def likeView(request,pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
         post.likes.add(request.user)
         liked = True
    return HttpResponseRedirect(reverse('myblog:article_detaile', args=[str(pk)]))


class HomeView(ListView):

    model= Post
    template_name = 'home.html'
    paginate_by = 4
    ordering = ['-post_date']

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context['cat_menu'] = cat_menu
        return context 

def CategorylistView(request):
    cat_menu_list= Category.objects.all()  
    return render(request, 'category_list.html' , {'cat_menu_list':cat_menu_list})


def CategoryView(request,cats):
    category_posts = Post.objects.filter(category=cats.replace('-' , ' ', ))
    return render(request, 'categories.html' ,{'cats':cats.title().replace('-' , ' ') , 'category_posts':category_posts})


class AboutView(TemplateView ):

    template_name = "about.html"

class ArticleDetalView(DetailView):
    model = Post
    #form_class  = PostForms
    template_name = 'articl_details.html'

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(ArticleDetalView, self).get_context_data(*args, **kwargs)

        stuff= get_object_or_404(Post,id=self.kwargs['pk'])
        total_likes = stuff.total_likes()
        
        liked = False
        if stuff.likes.filter(id=self.request.user.id).exists():
            liked = True 

        context['cat_menu'] = cat_menu
        context["total_likes"]= total_likes
        context["liked"] = liked
        return context      

class AddPostView(CreateView):
    model = Post
    form_class  = PostForms
    template_name = 'add_post.html'
    #hadi ila gay3amar post kalala o bkolchi lihadatih f jadwal d post 
    #fields = '__all__'
    #hadi  gay3amar dikchi ligathaddlo nta hna bla b jadwal li model
    #fields = ('title', 'body')

class AddCommentView(CreateView):
    model = Comment
    form_class  = CommentForm 
    #fields = '__all__'  
    template_name = 'add_comment.html'
    def form_valid(self,form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('myblog:home')
      
class AddCategorView(CreateView):
    model = Category
    #form_class  = PostForms
    template_name = 'add_category.html'
    #hadi ila gay3amar post kalala o bkolchi lihadatih f jadwal d post 
    fields = '__all__'
    #hadi  gay3amar dikchi ligathaddlo nta hna bla b jadwal li model
    #fields = ('title', 'body')

class UpdatePostView(UpdateView):
    model = Post
    template_name = 'update_post.html'
    form_class  = EditForm
    #fields = ['title' , 'title_tag','body']    

class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('myblog:home') 


######## view admin ######

class AdminLoginView(FormView):
    template_name = "adminpage/adminlogin.html"
    form_class = AdminLoginForm
    success_url = reverse_lazy("myblog:adminhome")

    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and Admin.objects.filter(user=usr).exists():
            login(self.request,usr)
        else:
             return render(self.request , self.template_name , {"form":self.form_class,"error":"Invalid credentails"})

        return super().form_valid(form)     

class AdminHome(TemplateView):

    template_name = "adminpage/adminhome.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and Admin.objects.filter(user=request.user).exists():
            pass
        else:
            return redirect("/admin-login/")
        return super().dispatch(request,*args ,**kwargs)

    def get_context_data(self, *args, **kwargs):
        cat_menu_admin = Post.objects.all()
        context = super(AdminHome, self).get_context_data(*args, **kwargs)
        context['cat_menu_admin'] = cat_menu_admin
        return context

def courMView(request):
    context = []
    return render(request, 'adminpage/motaki_dris.html' ,{})




##### 19:44

myblog/templates/add_category.html
{% extends "base.html" %}
{% block title%} Create a New Blog Category!{%  endblock %}
{% block content %}

{% if user.is_authenticated   %}
        <h1>Add Category.....</h1>
        <br>
        <div class="form-group">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-outline-secondary">Add Categery</button>
            </form>
            </div>

{% else%}
   You're  not allowed here! (and you know it .....)
{% endif  %}

{% endblock  %}

myblog/templates/add_comment.html
{% extends 'base.html'  %}
{% block title%} Comment On Blog Post{%  endblock %}
{% block content %}

        <h1>Add Comment...</h1>
        <br>
        <div class="form-group">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-outline-secondary">Add Comment</button>
            </form>
            </div>


{% endblock  %}

myblog/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Xmath{% endblock %}</title> 
    <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/mainepage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/folter.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/bolog_detil.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/about.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <style>
      

    </style>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-hover ">

  <a class="navbar-brand" href="{% url 'myblog:home'  %}">Xmath</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- Category Menu Code  -->
      {% if cat_menu  %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          {% for item in  cat_menu  %}
          <a class="dropdown-item" href="{% url 'myblog:category' item|slugify %}">
              {{ item}}</a>
          {% endfor  %}
        
        </div>
      </li>
      {%else%}
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myblog:category-list'  %}" > Categories</a>
          </li>

    {% endif %}

  

      {% if user.is_authenticated   %}
      <li class="nav-item">
        <a class="nav-link" href="#" >auter choise</a>
      </li>
    
      <!--
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myblog:add_post'  %}" > Add Post</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myblog:add_category'  %}" > Add Category</a>
      </li>
       -->


      {%else%}
      <li class="nav-item">
        <a class="nav-link"  href="{% url 'members:register'  %}" >Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  href="{% url 'login'  %}" >Login</a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'myblog:about'  %}"> Aboute</a>
       </li> 

      {% endif %}
    </ul>
   

    <form class="form-inline my-2 my-lg-0 ml-auto"> <!--nkadro nzidoha chwiya #ml-auto -->
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> 
    {% if user.is_authenticated   %} 
       
    <ul class="navbar-nav ml-auto">
     <!--  star dropdow--> 
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <samp style="color:bisque;"> {{user.last_name}}</samp>
          {% if user.profile.profile_pic %}
             <img class="rounded-circle" src="{{user.profile.profile_pic.url}}" width="30">
          {% endif %}   
      
        </a>
        <div class="dropdown-menu dropdown-menu  dropdown-menu-right  " aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'members:edit_profile'%}">Edit Setting</a>
          {% if user.profile.id %}
                <a class="dropdown-item" href="{% url 'members:edit_profil_page'  user.profile.id %}">Edit Profel Page</a>
                <a class="dropdown-item" href="{% url 'members:show_profil_page' user.profile.id %}">Show Profile Page</a>
                {% else  %}
                <a class="dropdown-item" href="{% url 'members:create_profil_page'%}">Create Profele Page</a>
          {% endif %} 
          <a class="dropdown-item"  href="{% url 'logout'  %}" >Logout</a>     
        </div>
      </li>

    </ul>
    {% endif %}
  
  </div>
</nav>

<body>
  <div class="abdu">
  <div class="boxtt">
    <div class="imgBx">
    <img src="{% static 'myblog/images/mmp.png'  %}">  
    </div>
    <div class="contentll">
      <h2>Jonh Doe <br><samp>Create Desiner</samp><br><a href="#">link</a></h2>
    </div>
  </div>
  <div class="boxtt">
    <div class="imgBx">
    <img src="{% static 'myblog/images/image6.png'  %} " >  
    </div>
    <div class="contentll">
      <h2>Jonh Doe<br><samp>Create Desiner</samp><br><a href="#">link</a></h2>
    </div>
  </div>
  
  <div class="boxtt">
    <div class="imgBx">
    <img src="{% static 'myblog/images/image5.png'  %}">  
    </div>
    <div class="contentll">
      <h2>Jonh Doe <br><samp>Create Desiner</samp><br><a href="#">link</a></h2>
    </div>
  </div>
  </div>
   <!-- and carousel -->
   <!-- 
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'myblog/images/school-books.jpg'  %}"  class="d-block w-100"  height="250" alt="...">

        <div class="carousel-caption d-none d-md-block">
          <h5 class="text-primary">First slide label</h5>
          <p class="text-primary">Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'myblog/images/school-books.jpg'  %}" class="d-block w-100" height="250" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 class="text-primary">Second slide label</h5>
          <p class="text-primary">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'myblog/images/school-books.jpg'  %}"class="d-block w-100 "  height="250" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 class="text-primary">Third slide label</h5>
          <p class="text-primary">Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true" ></span>
      <span class="sr-only">Next</span>
    </a>
  </div> -->
  <!-- star carousel  -->
  <!-- star maine page   -->

  <!-- and maine page -->
  <!-- star conttenaire -->
   <div class="container">
    {% block content %}

    {% endblock %}
  </div>
   <!-- and conttenaire -->
    <!-- satar  foolter -->
    <footer class="footer-section bg-dark">
      <div class="footer-top-section">
          <div class="container">
              <div class="row">
                  <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="single-fta">
                        <img src="{% static 'myblog/images/images-test.png'  %}" alt="nature" class="img-fluid" width="50" height="50">
                          <ul class="fta-list">
                              <li><a href="#"><span class="glyphicon glyphicon-chevron-right"></span> Finacial Planning</a></li>
                              <li><a href="#"><span class="glyphicon glyphicon-chevron-right"></span> Investments Management</a></li>
                              <li><a href="#"><span class="glyphicon glyphicon-chevron-right"></span>Taxes Planning</a></li>
                          </ul>
                      </div>
                  </div>
                  <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="single-fta">
                          <h3 class="fta-title">Important Link</h3>
                          <ul class="fta-list">
                              <li><a href="#"><i class="fa fa-square"></i>Finacial Planning</a></li>
                              <li><a href="#"><i class="fa fa-square"></i>Investments Management</a></li>
                              <li><a href="#"><i class="fa fa-square"></i>Taxes Planning</a></li>
                          </ul>
                      </div>
                  </div>
                  <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="single-fta">
                          <h3 class="fta-title">Important Link</h3>
                          <ul class="fta-list">
                              <li><a href="#"><i class="fa fa-square"></i>Finacial Planning</a></li>
                              <li><a href="#"><i class="fa fa-square"></i>Investments Management</a></li>
                              <li><a href="#"><i class="fa fa-square"></i>Taxes Planning</a></li>
                          </ul>
                      </div>
                  </div>
                  <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="single-fta">
                          <h3 class="fta-title">Contact Us</h3>
                          <ul class="fta-list">
                              <li>Address: 8th floor, 379 Hudson St, New York, NY 10018</li>
                              <li>Phone:0662897174</li>
                              <li>Email: benjaddiaberazeak@gmail.com</li>
                          </ul>

                      </div>
                  </div>
                  
              </div>
          </div>
      </div>
      <div class="footer-bottom-area">
          <div class="container">
              <div class="row">
                  <div class="col-xs-12">
                      <div class="footer-bottom">
                          <div class="row">
                              <div class="col-md-6 col-sm-12 col-xs-12">
                                  <div class="fba-copyright">
                                      <p>Copyright © 2020 Designed by Abderzak benjaadi</p>
                                  </div>
                              </div>
                              <div class="col-md-6 col-sm-12 col-xs-12">
                                  <div class="fba-links">
                                      <ul>
                                          <li><a href="#">About</a></li>
                                          <li><a href="#">Contact Us</a></li>
                                          <li><a href="#">Term & Conditions</a></li>
                                          <li><a href="#">Privacy Policy</a></li>
                                          <li><a href="#">Sites Map</a></li>
                                      </ul>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </footer>
   <!-- and foleter -->
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>

myblog/templates/categories.html
{% extends 'base.html'  %}
{% block title%}Home{%  endblock %}
{% block content %}
{% if category_posts  %}
    <h1>{{ cats }} Category</h1>
    {% for post in category_posts  %}
    <h6><a class="btn btn-info" href="{% url 'myblog:article_detaile' post.pk%}">{{post.title}}</a></h6><br>
    <h6>  {{post.author.first_name}}  - {{post.author.last_name}} | {{post.post_date}}</h6>
    <h6>{{post.body|slice:":200"|safe}}</h6>
    {% if user.is_authenticated   %}
    <a class="btn btn-primary" href="{% url 'myblog:updet_post' post.pk  %}">Edit Post</a>
    <a class="btn btn-primary" href="{% url 'myblog:delete_post' post.pk  %}">Delet Post</a>
{% endif %}   
{% endfor  %}
{% else %}
    <h2>Soruy This page does not exist</h2>
{% endif%}
{% endblock %}

myblog/templates/category_list.html
{% extends 'base.html'  %}
{% load static%}
{% block title%} Blog Categories{%  endblock %}
{% block content %}
   <h1>Blog Categories</h1>
   {% for item in  cat_menu_list %}
   <h4><a class="dropdown-item" href="{% url 'myblog:category' item|slugify %}">
       {{ item}}</a></h4>
   {% endfor  %}


{%  endblock  %}